export const WS_MESSAGES_TYPE = {
    USER_SUBSCRIBE: 0,
    USER_ADMIN_SUBSCRIBE: 1,
    battle_JOIN_QUEUE: 2,
    battle_RELAX_QUEUE: 3,
    battle_LEAVE_QUEUE: 4,
    battle_MATCH_FOUND: 5,
    battle_READY: 6,
    battle_READY_STATUS: 7,
    battle_MATCH_CANCELLED: 8,
    battle_DECLINE: 9,
    battle_MATCH_DECLINED: 10,
    battle_MATCH_START: 11,
    battle_PLAYER_ENTERED_BATTLE: 12,
    battle_ANSWER: 13,
    battle_ANSWER_SUMMARY: 14,
    battle_NEW_QUESTION: 15,
    battle_CHAT_MESSAGE: 16,
    battle_LEAVE_BATTLE: 17,
    battle_OVERTIME: 18,
    battle_START_OVERTIME: 19,
    battle_USER_ACTION: 20,
    battle_MATCH_FINISHED: 21,
    friends_BATTLE_REQUEST: 22,
    friends_BATTLE_WITHDRAW: 23,
    friends_BATTLE_AUTO_WITHDRAW: 24,
    friends_BATTLE_ACCEPT: 25,
    friends_BATTLE_DECLINE: 26,
    friends_REFRESH: 27,
    broadcast_REFRESH_FRIENDS: 28,
    admin_USER_BANNED: 29,
    admin_USER_UNBANNED: 30,
    admin_USER_DELETED: 31,
    admin_BAN_EXPIRED: 32,
    admin_USERS_ONLINE: 33,
}

export const ACTION_TYPE = {
    HIDE_2_WRONG_ANSWERS: 0,
    HALF_THE_TIME_OPPONENT: 1,
    DOUBLE_NEGATIVE_POINTS_OPPONENT: 2,
}